### ISSUE TITLE
./run_server.sh not finding Experiments tables when first run

### ISSUE THREAD

**Issue by extrajoss** [ODonoghueLab/versus#40]
So I followed the readme for install
cloned and ran npm install for both client and server
and then ran 
versus/server>./run_server.sh
here is the result.

> [nodemon] 1.12.1
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching: /Users/jos031/Code/Repos/versus/server/src/**/*
> [nodemon] starting `node src/bin/www`
> Serving on localhost:3000
> Executing (default): SELECT `Experiment`.`id`, `Experiment`.`attr`, `Experiment`.`createdAt`, `Experiment`.`updatedAt`, `images`.`id` AS `images.id`, `images`.`url` AS `images.url`, `images`.`filename` AS `images.filename`, `images`.`createdAt` AS `images.createdAt`, `images`.`updatedAt` AS `images.updatedAt`, `images`.`ExperimentId` AS `images.ExperimentId` FROM `Experiments` AS `Experiment` LEFT OUTER JOIN `Images` AS `images` ON `Experiment`.`id` = `images`.`ExperimentId`;
> (node:55947) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SequelizeDatabaseError: SQLITE_ERROR: no such table: Experiments
> (node:55947) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

When I look in the SQLite database though 

> sqlite> .fullschema
> CREATE TABLE `Users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(255), `email` VARCHAR(255) UNIQUE, `password` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, UNIQUE (`email`));
> CREATE TABLE `Experiments` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `attr` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
> CREATE TABLE `Images` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `url` VARCHAR(255), `filename` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `ExperimentId` INTEGER REFERENCES `Experiments` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);
> CREATE TABLE `Participants` (`participateId` UUID PRIMARY KEY, `attr` TEXT, `states` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `ExperimentId` INTEGER REFERENCES `Experiments` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);
> CREATE TABLE `UserExperiments` (`permission` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `ExperimentId` INTEGER NOT NULL REFERENCES `Experiments` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `UserId` INTEGER NOT NULL REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY (`ExperimentId`, `UserId`));
> /* No STAT tables available */

so looks like the tables are there.

When I run 
versus/server>./run_server.sh
a second time it all seems to work. So probably a timing thing that its attempting to run the query before its finished building the tables?

**Comment by boscoh** [comment]
Fixed in https://github.com/ODonoghueLab/versus/commit/a7dc9d4eaf9cab5808fb29069f3330bff8581e48
