### ISSUE TITLE
can't change email address

### ISSUE THREAD

**Issue by extrajoss** [ODonoghueLab/versus#42]
On edit user I attempted to change my email address.

in the logs I can see

POST /api/rpc-run 200 214.295 ms - 16
Executing (default): SELECT `id`, `name`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`id` = 1;
>> router.rpc-run.login
Executing (default): SELECT `id`, `name`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`email` = 'my email address' LIMIT 1;
>> router.rpc-run.login no user found
POST /api/rpc-run 200 104.559 ms - 49

once again no feed back on the client side so not aware that change hasn't happened.

If the email address is how you are retrieving the user probably shouldn't be able to change it. Either that or retrieve by user id?

**Comment by extrajoss** [comment]
Actually the update doesn't seem to work no matter what I put in. So the email address change was a red herring. Its not finding by user id either.

**Comment by boscoh** [comment]
fixed with https://github.com/ODonoghueLab/versus/commit/a01ba4cdfd03d6ebd84362c1ef09e515653fa68f
