### ISSUE TITLE
Missing first image

### ISSUE THREAD

**Issue by extrajoss** [ODonoghueLab/versus#43]
I uploaded 5 images but in the pairings an image only appears in the second slot. 
I can't click on the first slot and if I click on the second slot I get the below error:

> >> router.rpc-run.publicChooseItem
> Executing (default): SELECT `participateId`, `attr`, `states`, `createdAt`, `updatedAt`, `ExperimentId` FROM `Participants` AS `Participant` WHERE `Participant`.`participateId` = '93a70bb2-ba0a-4b94-85da-5a7460a970dc';
> Executing (default): SELECT `Experiment`.`id`, `Experiment`.`attr`, `Experiment`.`createdAt`, `Experiment`.`updatedAt`, `images`.`id` AS `images.id`, `images`.`url` AS `images.url`, `images`.`filename` AS `images.filename`, `images`.`createdAt` AS `images.createdAt`, `images`.`updatedAt` AS `images.updatedAt`, `images`.`ExperimentId` AS `images.ExperimentId`, `Users`.`id` AS `Users.id`, `Users`.`name` AS `Users.name`, `Users`.`email` AS `Users.email`, `Users`.`password` AS `Users.password`, `Users`.`createdAt` AS `Users.createdAt`, `Users`.`updatedAt` AS `Users.updatedAt`, `Users.UserExperiment`.`permission` AS `Users.UserExperiment.permission`, `Users.UserExperiment`.`createdAt` AS `Users.UserExperiment.createdAt`, `Users.UserExperiment`.`updatedAt` AS `Users.UserExperiment.updatedAt`, `Users.UserExperiment`.`ExperimentId` AS `Users.UserExperiment.ExperimentId`, `Users.UserExperiment`.`UserId` AS `Users.UserExperiment.UserId`, `participants`.`participateId` AS `participants.participateId`, `participants`.`attr` AS `participants.attr`, `participants`.`states` AS `participants.states`, `participants`.`createdAt` AS `participants.createdAt`, `participants`.`updatedAt` AS `participants.updatedAt`, `participants`.`ExperimentId` AS `participants.ExperimentId` FROM `Experiments` AS `Experiment` LEFT OUTER JOIN `Images` AS `images` ON `Experiment`.`id` = `images`.`ExperimentId` LEFT OUTER JOIN `UserExperiments` AS `Users.UserExperiment` ON `Experiment`.`id` = `Users.UserExperiment`.`ExperimentId` LEFT OUTER JOIN `Users` AS `Users` ON `Users`.`id` = `Users.UserExperiment`.`UserId` LEFT OUTER JOIN `Participants` AS `participants` ON `Experiment`.`id` = `participants`.`ExperimentId` WHERE `Experiment`.`id` = 2;
> (node:56007) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Path must be a string. Received undefined

![screen shot 2017-11-08 at 1 40 36 pm](https://user-images.githubusercontent.com/2870843/32529136-e843eb5a-c48a-11e7-8a17-b4df86beacc6.png)

**Comment by boscoh** [comment]
fixed with https://github.com/ODonoghueLab/versus/commit/3577f7732126312c8d3e854f3b17505d226a7f38
