### ISSUE TITLE
Randomisation of the answer position is not normally distributed. 

### ISSUE THREAD

**Issue by benedettafrida** [ODonoghueLab/versus#44]
While I was trying to set up the analysis pipeline, I discover something very worrying: we have an overall bias for correct answers. To better explain the issue I will go through the analysis. 
I recorded data from experiments in which I always click on the same position throughout the experiment:  I did this from position1 to pos5 ( 5 multiple choices). 
For each position, I recorded 5 experiments in which I set the probability of repetitions to 1, so I have 30 question each run, for a total of 150 questions per position. 
I then checked the number of correct answers vs the total. In theory, this should be around 1/5 ( ~20% ) instead it’s at ~60%. I’m uploading a plot in which I also grouped the results by question (set1-15) and position (pos1-5); Beware that in order to see overlapping points I introduced jittering on the y-axis.

[plot.pdf](https://github.com/ODonoghueLab/versus/files/1888458/plot.pdf)
[ClickingSamePosition.zip](https://github.com/ODonoghueLab/versus/files/1888459/ClickingSamePosition.zip)

**Comment by boscoh** [comment]
Thanks Benedetta. I've been looking at this today. No luck so far.

**Comment by boscoh** [comment]
Just a little note: this had me confused for a while. Instead of 'normal distribution', I think you mean [uniform distribution](https://en.wikipedia.org/wiki/Discrete_uniform_distribution). In statistics, [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) typically refers to the Gaussian distribution.

**Comment by boscoh** [comment]
I found the bug - I wasn't extracting the correct value for each question correctly. The supposed "correct" answer was just a repeat of the "chosen" answer. This shoud be fixed now. Could you re-download the results and run your scripts to check? I've checked the stats on my computer and it gives ~20%.

**Comment by benedettafrida** [comment]
I am not sure what you mean by

>  I wasn't extracting the correct value for each question correctly. The supposed "correct" answer was just a repeat of the "chosen" answer

I can run the test again sure.. it will take some time though. I could schedule in tomorrow.  
Question: when you say 

> I've checked the stats on my computer and it gives ~20%

you mean you ran a test like the one I did?

**Comment by boscoh** [comment]
It means that the bug is that in results.csv, the Answer and the Chosen are the same for the non-repeat rows. 

To test, you just re-download the results.csv and run your scripts. I wrote my own test scripts to emulate what you did in R.

**Comment by benedettafrida** [comment]
Hi Bosco. 
Did another couple tests like the previous one.  All seems much better, thanks.
