### ISSUE TITLE
Issues understanding parameter 'Probability of repeats'

### ISSUE THREAD

**Issue by jnyvng** [ODonoghueLab/versus#46]
In the viewpoint study that Julian and I worked on together, the percentage of repeats was 100%, i.e. we repeated all image pairs. After speaking to Sandeep about the Aesthetics study and looking at her code, I think I understand that what you call the probability of repeating a specific question refers to the probability of getting a success using a binomial distribution? On a quick glance at Sandeep's code, I believe she coded a Bernoulli distribution (because N is set to 1) to get a probability of success at an unfair coin toss (because she set the probability to 0.2) - please correct me if I am wrong. I am confused because in Versus, when I set the _Probability of Repeat_ to _0.5_, the following text appears:

```Number of questions (including possible qualification): 34     Number of repeats: 17```

This would be correct if the percentage is referring to the percentage of repeated questions but would be incorrect if it was following a Bernoulli distribution. Can you clarify this?

In the original PHP code by Sandeep - if I understood correctly - she used a binomial distribution to determine whether a question should be repeated or not (with a probability of 0.2), to minimize the number of repeats needed to get a significant result when testing for consistency - furthermore, we do not know how many questions there are in a 2AFC study, so setting a percentage of repeated questions might not be useful.

Saying that, if a percentage of repeats is easier for you to code (like Benedetta wants for the Rondo Study), I am also Ok with that, but in that case, we need to change the name of this parameter -> need to discuss this.

**Comment by boscoh** [comment]
I have implemented the probability as per Sandeep's code in the folder that Julien sent me `Aesthetics/Versus2`.

In that folder, a variable `$probability = 0.2` is defined in `variables.php` in line 5.

This is used in two places:
1. `experiment.php` line 101: `paired_displayNextImages($workerId, $expPage, $probability)`
2. `mturkers.php` line 61: `createUserInDB($workerId, $assignmentId, $mturkSubmissionUrl, $probability);`

In both cases, a `probability` is used, and I have followed the same terminology.

For case 1, as you mentioned, it encodes a Bernoulli trial (not really used as a distribution) for whether a repeat will be shown.

For case 2, eventually `numRespRepeats` is calculated and put in the database, using the formula in `be_functions.php` in line 58. This is the formula that I have used to calculate the `Number of repeats`.

This variable `numRespRepeats` in the database is used to determine the maximum number of repeats that are performed. This variable is retrieved in the function `isRepeatsDone` which is used in the calculation for repeats in `exp_functions.php` line 137

As far as I can see, this version of the code does not repeat 100% of the pairings. If `$probability` is low, there is a good chance that `numRespRepeats` of repeats will be seen. But if $probability is high, then this is not guaranteed, unless we show all the repeats at the end.

**Comment by boscoh** [comment]
As far as I can see, there are two possibilities (both easy to code):

1. Set a probability for repeats, and allow a variable number of repeats
2. Set a percentage of repeats, and a probability of interleaved repeats, with the possibility of showing a bunch of dangling repeats at the end.

If `$probability` is low, both cases converge most of the time, as in the case with Sandeep's code. I did not realise that one would set a high probability, so in that case, you would have to decide which you would prefer.

Another issue is that if '$probability` is high for the repeats, then one would lose the sense of 'interleaving' repeats.

Which do you prefer?
