### ISSUE TITLE
Position of images in the repeat questions

### ISSUE THREAD

**Issue by jnyvng** [ODonoghueLab/versus#47]
In the viewpoint paper, we always made sure that the repeated image pairs are not in the same position as the first time the image pair has been shown, i.e. if the order was "imageA imageB" the first time it was shown, the second time we show that image pair, the order was "imageB imageA".

**Comment by boscoh** [comment]
It should do this. Appears to work on my end. Please check.

**Comment by boscoh** [comment]
Currently, even though the repeats are displayed in the results.csv, the data structure doesn't save the repeats as a separate comparison, it just writes the repeat value in the data structure of the original comparison. Thus in the results.csv, the repeat is always written after its original comparison.

As far as I know, I've added code that always reverses the order of the images for a repeat.

To check the repeats during the experiment, open the developer console and track the output:

![screen shot 2018-05-09 at 2 15 23 pm](https://user-images.githubusercontent.com/180224/39795651-f8683420-5394-11e8-8415-7969507efde0.png)
