### ISSUE TITLE
Versus crashes when setting parameter "Probability of repeats" to 1

### ISSUE THREAD

**Issue by jnyvng** [ODonoghueLab/versus#51]
This, of course, depends on what the parameter "Probability of repeats" refers to. If it refers to the percentage of repeated questions, then I will need to be able to repeat all questions, i.e. set the probability of repeats to 1.

**Comment by boscoh** [comment]
As explained in issue #46, I implemented "Probability of Repeats" as per Sandeep's code-base, where the variable $probability is used for two purposes. Her algorithm would not be able to repeat all pairings. 

I can change it to do so. Btw, do you have access to the code that you and Julien wrote that has implemented that functionality?

**Comment by jnyvng** [comment]
I believe you don't need more information on this? If so: we need probability to perform a repeat at a specific time point (which was the 0.2) and a separate value for the percentage of questions to be repeated so I can set this to 1, if I want to repeat all the questions.
