### ISSUE TITLE
Versus crashes

### ISSUE THREAD

**Issue by jnyvng** [ODonoghueLab/versus#53]
See screenshot, I set the "Probability of repeats" to 0.2, and the number of images was 10, other than that, I didn't do anything specific.

![screen shot 2018-04-12 at 08 31 01](https://user-images.githubusercontent.com/16753531/38646654-25f42f44-3e2c-11e8-8b02-38ec5bc44b47.png)

**Comment by boscoh** [comment]
Should be fixed. Please check that new experiments don't crash.
