### ISSUE TITLE
Versus is stuck on loading image

### ISSUE THREAD

**Issue by jnyvng** [ODonoghueLab/versus#55]
I have set the probability of repeats to 0.3, uploaded 20 images, and ran the experiment, about halfway through, the images stopped loading. I've been waiting for 10 minutes now and nothing happens, see screenshot.

![screen shot 2018-04-12 at 09 18 04](https://user-images.githubusercontent.com/16753531/38648021-9157623c-3e32-11e8-9144-172af67c27c2.png)

**Comment by boscoh** [comment]
related to #53. closed.
