### ISSUE TITLE
Clicking on the Versus logo when user is already signed in

### ISSUE THREAD

**Issue by jnyvng** [ODonoghueLab/versus#58]
If I am already logged in, and I click on the Versus logo, I see the Welcome page with Login and Register button. Is it possible to comment out the Please Login or Register if the user is already logged in?
![screen shot 2018-04-19 at 10 52 44](https://user-images.githubusercontent.com/16753531/38965415-080c8014-43c0-11e8-9c0f-8aaceaa2699d.png)

**Comment by boscoh** [comment]
commit ecfa4e6
