### ISSUE TITLE
Versus description is wrong

### ISSUE THREAD

**Issue by jnyvng** [ODonoghueLab/versus#59]
Is it possible to change the description of the Versus on the first page, as it is no longer correct?

Please change the following:

"
Versus is a tool to facilitate the complete ranking of a set of images for visual quality analysis. It is designed to work both locally and with Mechanical Turk.

Currently, we provide:
1. two-alternative forced-choice (2FCA) option, whereby images a ranked via a series of comparisons between two images.
2. multiple choice option with a qualification round

Repository and further instructions at https://github.com/ODonoghueLab/versus

To setup a set of images for analysis:

Please Login or Register
"

to:

"
Versus is a tool to facilitate visual analytics studies. It is designed to work both as a standalone tool or to use in conjunction with Mechanical Turk as a survey link.

Currently, we provide 2 options:
1. Two-alternative forced-choice (2FCA) methodology to achieve a full-set image ranking by comparing image pairs in several rounds.
2. Multiple choice survey with a possible qualification round to record participant answers.

Repository and further instructions at https://github.com/ODonoghueLab/versus

Login or Register
"

**Comment by boscoh** [comment]
commit https://github.com/ODonoghueLab/versus/commit/ecfa4e6ff36447162fef91ebd3616d0fe183136b
