### ISSUE TITLE
Repeat questions are not present in the results.csv file

### ISSUE THREAD

**Issue by jnyvng** [ODonoghueLab/versus#61]
I cannot find the results for the repeat questions in the results.csv file, see attachment.

[1May2018_Results.txt](https://github.com/ODonoghueLab/versus/files/1962605/1May2018_Results.txt)

**Comment by boscoh** [comment]
added repeats in csv https://github.com/ODonoghueLab/versus/commit/c2d549c1abe1b2e5a3af597d9d61a8cb5bb9809e
